# -*- coding: utf-8 -*-
"""Desafios_biopython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NZ5jhkbcXscd7yQ6PScX0CzkUU21ON4z

# **Desafios Práticos com Biopython: BLAST Online, Entrez e SeqIO Integrados**
---

Olá! Chegou a hora de colocar a mão na massa e aplicar tudo o que aprendemos sobre Biopython! Estes desafios foram cuidadosamente elaborados para que vocês possam integrar o uso dos módulos Bio.Entrez (para busca e download de dados), Bio.SeqIO (para manipulação de arquivos de sequência) e Bio.Blast.NCBIWWW (para realizar buscas por similaridade online).

Lembrem-se que é crucial configurar o seu e-mail no Entrez e no Blast.

## **Desafio 1: Anotando um Gene de Levedura Desconhecido**

Você está trabalhando com dados de sequenciamento de *Saccharomyces cerevisiae* (levedura de padaria) e acabou de obter um fragmento de DNA que parece ser parte de um gene. Sua missão é usar as ferramentas do Biopython para tentar identificar esse gene e inferir sua possível função.
"""

# Installing BioPython
!pip install biopython

"""**Sua Tarefa:**

1. Blast Online: Realize uma busca `blastn` no NCBI (`Bio.Blast.NCBIWWW`) utilizando a sequência acima como sua consulta. Aponte a busca para o banco de dados `nr` (Nucleotide Collection). Defina um E-value máximo de `1e-10` e limite a lista de hits retornados para os 5 melhores (`hitlist_size=5`). Salve a saída XML do BLAST em um arquivo chamado `blast_results_levedura.xml`.   
2. Análise do Melhor Hit: Usando `Bio.Blast.NCBIXML`, leia o arquivo `blast_results_levedura.xml`. Encontre o melhor hit (aquele com o menor E-value). Imprima no console o ID de acesso (`Accession Number`) e o título completo desse melhor hit.   
3. Download da Sequência Completa: Com o `Accession Number` do melhor hit em mãos, utilize `Bio.Entrez.efetch` para baixar a sequência completa desse gene do banco de dados nucleotide do NCBI, no formato FASTA.
4. Salvamento e Verificação: `Use Bio.SeqIO.read` para carregar a sequência que você acabou de baixar e, em seguida, salve-a em um novo arquivo FASTA chamado `melhor_hit_levedura.fasta`. Imprima no console o ID, a descrição e o comprimento dessa sequência completa baixada para confirmar que tudo correu bem.
"""

# Código para executar BLAST online (QBlast) usando Entrez para submissão e recuperação

from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML
from Bio import Entrez
from Bio import SeqIO
from Bio.Seq import Seq # Importar Seq diretamente
import os

# --- Accese ao seu Google Drive ---

# --- Mude o path até a pasta onde está o arquivo ---

# --- Configurações Iniciais ---

# --- Passo 1: Sequência de Consulta ---

# --- Passo 2: BLAST Online (NCBIWWW) ---

# --- Passo 3: Análise dos Resultados (NCBIXML) ---

# --- Passo 4: Download da Sequência Completa (Entrez e SeqIO) ---

# --- Salva a sequência completa em um novo arquivo FASTA ---

"""## **Desafio 2: Investigando a Conservação da Insulina em Mamíferos**

Você tem curiosidade sobre quão conservada a proteína insulina é entre diferentes espécies de mamíferos. Este desafio o guiará na obtenção dessas sequências e na sua comparação usando o BLAST online.

**Sua Tarefa:**

1. Busca e Download de Sequências:  
Utilize Bio.Entrez.esearch para buscar sequências da proteína insulina (insulin [PROTEIN]) especificamente das espécies Homo sapiens, Mus musculus, Rattus norvegicus e Bos taurus no banco de dados protein do NCBI.   
Com os IDs retornados, use Bio.Entrez.efetch para baixar as sequências dessas proteínas no formato FASTA.
Salve todas as sequências baixadas em um único arquivo FASTA multi-entrada chamado insulinas_mamiferos.fasta.
2. Consulta da Insulina Humana:
A partir do arquivo insulinas_mamiferos.fasta, identifique e selecione a sequência da insulina humana como sua sequência de consulta.   
3. Blast Online:
Submeta a sequência da insulina humana para uma busca blastp contra o banco de dados nr (Non-redundant protein sequences) do NCBI.
Defina um E-value máximo de 1e-5 e um limite de hitlist_size=10. Salve a saída XML em blast_insulina_humana_vs_nr.xml.
4. Análise Detalhada dos Hits:
Usando Bio.Blast.NCBIXML, parseie o arquivo blast_insulina_humana_vs_nr.xml.
Para cada hit (alinhamento), imprima no console:
* O título completo do hit.
* O Accession Number.
* O E-value do melhor HSP (High-scoring Segment Pair).    
* A porcentagem de identidade do melhor HSP.  

**Desafio Extra:** Tente extrair e imprimir o nome do organismo e, se possível, o nome do gene/proteína a partir do título do hit (Dica: pense em como usar funções de string como split() ou expressões regulares).
"""

from Bio import Entrez
from Bio import SeqIO
from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML
from Bio.Seq import Seq
import os
import re # Para extração de informações do título
import time # Para pausas entre requisições

# --- Configurações Iniciais ---

# --- Passo 1: Busca e Download de Sequências (Entrez e SeqIO) ---

# --- Passo 2: Preparar Sequência de Consulta (Insulina Humana) ---

# --- Passo 3: BLAST Online (NCBIWWW) da Insulina Humana contra 'nr' ---

# --- Passo 4: Análise e Filtragem dos Resultados (NCBIXML) ---

"""## **Desafio 3: Identificação de uma Nova Sequência de mRNA em um Projeto de Pesquisa**
---

Imagine que você recebeu um arquivo contendo várias sequências de mRNA curtas de um projeto de sequenciamento. Seu objetivo é identificar rapidamente a qual organismo e gene cada uma dessas sequências pertence usando o BLAST online e gerar um relatório conciso.  

Sequências de mRNA de Consulta:  

Crie um arquivo FASTA chamado mRNAs_desconhecidos.fasta com as seguintes sequências:   

```
>mRNA_1
AGGTCATGTACGATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATG
>mRNA_2
TGCGCGTGCGCGTGCGCGTGCGCGTGCGCGTGCGCGTGCGCGTGCGCGTGCGCGTGCGC
>mRNA_3
GCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGCTAGC
```

**Sua Tarefa:**

1. Processamento de Múltiplas Consultas:
Leia o arquivo mRNAs_desconhecidos.fasta usando Bio.SeqIO.parse para obter cada SeqRecord individualmente.
Para cada SeqRecord (cada mRNA):
* Submeta-o a uma busca blastn contra o banco de dados nr do NCBI.
* Defina um E-value máximo de 1e-5 e limite o número de hits a 3.
* ATENÇÃO: Para não sobrecarregar os servidores do NCBI, inclua uma pausa de time.sleep(5) (5 segundos) entre cada submissão de BLAST.
* Salve a saída XML de cada busca em um arquivo separado, por exemplo, blast_mRNA_1.xml, blast_mRNA_2.xml, etc., dentro de um diretório que você pode criar para organizar os resultados (e.g., blast_mRNA_results/).
2. Geração de Relatório Personalizado:
Após todas as buscas serem concluídas e salvas, itere sobre os arquivos XML gerados.
Para cada arquivo XML, parseie-o e extraia as seguintes informações do melhor hit (o primeiro alinhamento encontrado):
* O ID da sequência de consulta (o mRNA_X).
* O Accession Number do hit.
* O título completo do hit.
* O E-value do melhor HSP.
* A porcentagem de identidade do melhor HSP.
3. Imprima essas informações no console de forma organizada e legível, como um pequeno relatório para cada mRNA.
"""

from Bio.Blast import NCBIWWW
from Bio.Blast import NCBIXML
from Bio import SeqIO
from Bio.Seq import Seq # Importar Seq diretamente
import os
import time # Para pausas entre requisições
import re # Para extração de informações

# --- Configurações Iniciais ---

# --- Passo 1: Criação do Arquivo de Múltiplas Consultas (SeqIO) ---

# --- Passo 2: BLAST Online de Múltiplas Consultas (NCBIWWW) ---

# --- Passo 3: Processamento e Relatório Personalizado ---

"""Este caderno foi criado com ♥ pela [Natalia Coutouné]().   
Dúvidas? Pode-me escrever ao meu [email](nat.coutoune@gmail.com) 📧.
"""